server:
  port: 8081
  context-path: /

spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size : 500MB

elasticsearch:
  host: localhost
  port: 9200
  protocol: http
  rest:
    connection-timeout: 3600000
  apikey: UXlsRmlvNEJpT0VwcmRBVEhtcjU6d2htQ25nYnhSSC1FRmROUFhidmNDdw==
  url: https://localhost:3333/es