server:
  port: 8081
  context-path: /

spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size : 500MB

elasticsearch:
  ip: localhost
  port: 9200
  protocol: http
  rest:
    connection-timeout: 3600000

jwt:
  header: Authorization

  # (초)

logging:
  level:
    org:
      springframework:
        data:
          elasticsearch: DEBUG

cors:
  url: http://115.95.23.27:1234