server:
  port: 8081
  context-path: /

spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size : 500MB

elasticsearch:
  host: localhost
  port: 3333
  protocol: http
#  rest:
#    connection-timeout: 3600000
  apikey: cy1UcW1ZNEJyM2lCZUFaM2l6alQ6b3hWTnZWYmpSdUc1QnB1LXhIaklRUQ==
  userName: elastic
  password: 12341234