server:
  port: 8081
  context-path: /

spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size : 500MB
cors:
  sourceUrl: http://localhost:3000

elasticsearch:
  host: localhost
  port: 3333
  protocol: http
  apikey: TjF6YnFvOEJ3UHV1bWlkWW14TEQ6cnNpRlNNRU5UT1NUQzlBLTlkTklFUQ==
  userName: elastic
  password: 12341234
  idxName: book
  settingMappingPath: /Users/jihunjang/workspace/BookSearcher/backend/src/main/java/com/jihun/booksearcher/elasticSearch/config/settingAndMapping.json
  bulkSize: 10000
