server:
  port: 8081
  context-path: /

spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size : 500MB

elasticsearch:
  host: localhost
  port: 3333
  protocol: http
#  rest:
#    connection-timeout: 3600000
#  apikey: QVExRG40NEJiemRPbGxFVEF3LXI6YWtIa0FfbmZTVC1sd2lMY1dzQ2s0UQ==
  apikey: WUJ0dzBvNEJJUHJWUkItQjFBbWo6ZjlnTHk2VXJTdGlBY1hIWFU0eW9BZw==
  userName: elastic
  password: 12341234