server:
  port: 8081
  context-path: /

spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size : 500MB
cors:
  sourceUrl: http://localhost:3000

elasticsearch:
  host: localhost
  port: 3333
  protocol: http
#  apikey: TDZrcC1ZNEJiaGxzbmZRWnduZUo6TGRpald4UVFSd2l2RVpsOEdvRmhSQQ==
  apikey: ZEVybGxZOEJpUG1nYWpmLWp6djA6N1E4RkpkOTBRV3F1eURGVmQ3VDN3QQ==
  userName: elastic
  password: 12341234
  idxName: book
  settingMappingPath: src/main/java/com/jihun/booksearcher/elasticSearch/config/settingAndMapping.json
  bulkSize: 1000
